CREATE DATABASE IF NOT EXISTS new_data_base;
CREATE TABLE IF NOT EXISTS user (id INT, name VARCHAR(256) NOT NULL);
CREATE TABLE IF NOT EXISTS nationality (id INT NOT NULL, name VARCHAR(256) NOT NULL);